import Link from "next/link";
import { createPageMetadata } from "@/lib/metadata";
import { CheckCircle2, Download, KeyRound, PlayCircle } from "lucide-react";
import { PageHero } from "@/components/PageHero";
import { DeviceCard } from "@/components/DeviceCard";
import { SectionHeading } from "@/components/SectionHeading";
import { CTASection } from "@/components/CTASection";
import { devices } from "@/lib/devices";

export const metadata = createPageMetadata({ title: "App & Installation Guide", description: "Learn how to install FreeGoTV using general device setup steps. Confirm the correct app and compatibility before downloading or entering subscription details.", path: "/install" });
const steps = [{ icon: Download, title: "Download", text: "Confirm the correct app for your device in your setup instructions, then download it from its official source." }, { icon: CheckCircle2, title: "Install", text: "Install the application and complete any on-screen device setup." }, { icon: KeyRound, title: "Sign in", text: "Enter the authorized subscription details we provide after activation." }, { icon: PlayCircle, title: "Start streaming", text: "Explore the guide and enjoy the programming available to you." }];

export default function InstallPage() { return <><PageHero eyebrow="SETUP HUB" title={<>How to <span className="text-gradient">Install FreeGoTV</span></>} description="Looking for a FreeGoTV app? Start with your device and the general steps below. Confirm the app name and compatibility in your setup instructions before downloading." /><section className="section-space bg-[var(--mist)]" id="devices"><div className="container-page"><SectionHeading eyebrow="CHOOSE YOUR SCREEN" title="Set up on the devices you love." /><p className="mt-5 max-w-3xl leading-7 text-zinc-600">These are device categories listed by FreeGoTV, not app download links or model-specific instructions. The app and setup can vary by device. Review <Link href="/faq" className="font-bold text-[var(--primary-dark)] underline underline-offset-4">device and subscription questions</Link> before getting started.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{devices.map((device) => <DeviceCard key={device.name} device={device} />)}</div></div></section><section className="section-space bg-white" id="guides"><div className="container-page"><SectionHeading eyebrow="THE GENERAL FLOW" title="Four straightforward setup steps." align="center" /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{steps.map((step, index) => <article key={step.title} className="relative rounded-3xl border border-zinc-200 p-6"><span className="text-sm font-black text-[var(--primary-dark)]">Step {index + 1}</span><div className="mt-5 grid h-11 w-11 place-items-center rounded-2xl bg-zinc-950 text-white"><step.icon className="h-5 w-5" /></div><h3 className="mt-5 text-lg font-black">{step.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-600">{step.text}</p></article>)}</div></div></section><CTASection title="Need a hand with your device?" text="Our support team can help identify the best approved setup for your screen." /></>;
}
