import { CheckCircle2, Play, Users } from "lucide-react";

export function ResellerVisual() {
  return <div className="relative mx-auto w-full max-w-lg py-6">
    <div className="absolute inset-8 rounded-full bg-red-600/20 blur-3xl" />
    <div className="relative rounded-[2rem] border border-white/15 bg-zinc-900 p-4 shadow-2xl"><div className="rounded-[1.45rem] border border-white/10 bg-gradient-to-br from-zinc-800 to-zinc-950 p-5"><div className="flex items-center justify-between"><span className="text-sm font-black">Partner workspace</span><span className="rounded-full bg-red-400/15 px-2 py-1 text-xs font-bold text-red-200">FreeGoTV</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/5 p-4"><Users className="h-5 w-5 text-red-400" /><p className="mt-4 text-xs text-zinc-400">Customer records</p><p className="mt-1 text-lg font-black">Organized access</p></div><div className="rounded-2xl bg-white/5 p-4"><CheckCircle2 className="h-5 w-5 text-red-400" /><p className="mt-4 text-xs text-zinc-400">Setup notes</p><p className="mt-1 text-lg font-black">Clear workflow</p></div></div><div className="mt-4 rounded-2xl bg-white/5 p-4"><p className="text-sm font-black">Reseller discussion</p><p className="mt-2 text-sm leading-6 text-zinc-400">Contact FreeGoTV to review options, requirements and support expectations.</p></div></div></div>
    <div className="absolute -bottom-2 left-0 flex items-center gap-2 rounded-2xl border border-white/10 bg-zinc-800 px-4 py-3 shadow-xl sm:-left-5"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[var(--primary)]"><Play className="h-4 w-4 fill-white" /></span><span className="text-xs font-bold">Simple activation<br /><span className="font-normal text-zinc-400">for your clients</span></span></div>
  </div>;
}
